package Calculators.Enums;

public enum AreaEnum {
	SquaremileToSquarefoot,
	SquareinchToSquarefoot,
	HectareToSquarefoot,
	SquareyardToSquarefoot,
	SquaremeterToSquarefoot,
	AcreToSquarefoot,
	SquaremileToSquareinch,
	SquarefootToSquareinch,
	HectareToSquareinch,
	SquareyardToSquareinch,
	SquaremeterToSquareinch,
	AcreToSquareinch,
	SquaremileToHectare,
	SquarefootToHectare,
	SquareinchToHectare,
	SquareyardToHectare,
	SquaremeterToHectare,
	AcreToHectare,
	SquaremileToAcre,
	SquarefootToAcre,
	SquareinchToAcre,
	HectareToAcre,
	SquareyardToAcre,
	SquaremeterToAcre,
	SquaremileToSquareyard,
	SquarefootToSquareyard,
	SquareinchToSquareyard,
	HectareToSquareyard,
	SquaremeterToSquareyard,
	AcreToSquareyard,
	SquarefootToSquaremile,
	SquareinchToSquaremile,
	HectareToSquaremile,
	SquareyardToSquaremile,
	SquaremeterToSquaremile,
	AcreToSquaremile,
	SquaremileToSquaremeter,
	SquarefootToSquaremeter,
	SquareinchToSquaremeter,
	HectareToSquaremeter,
	SquareyardToSquaremeter,
	AcreToSquaremeter

}
