package Calculators.Operations.UnitTypes;

import Calculators.Operations.Operation;
import Calculators.Operations.BasicConversionOperations.GeneralConversion;
import Calculators.Windows.UnitConverterWindow;
import Controllers.UnitConverterController;

public class VolumeOperation extends Operation
{
	private final static GeneralConversion CubicFootToCubicInch = new GeneralConversion( 1728);
	private final static GeneralConversion CubicFootToCubicMeter = new GeneralConversion( 1/35.315);
	private final static GeneralConversion CubicFootToLiter = new GeneralConversion( 28.317);
	private final static GeneralConversion CubicFootToMilliliter = new GeneralConversion( 28317);
	private final static GeneralConversion CubicFootToUSCup = new GeneralConversion( 118);
	private final static GeneralConversion CubicFootToUSFluidOunce = new GeneralConversion( 958);
	private final static GeneralConversion CubicFootToUSGallon = new GeneralConversion( 7.481);
	private final static GeneralConversion CubicFootToUSPint = new GeneralConversion( 59.844);
	private final static GeneralConversion CubicFootToUSQuart = new GeneralConversion( 29.922);
	private final static GeneralConversion CubicFootToUSTablespoon = new GeneralConversion( 1915);
	private final static GeneralConversion CubicFootToUSTeaspoon = new GeneralConversion( 5745);
	
	private final static GeneralConversion CubicInchToCubicFoot = new GeneralConversion( 1.0/1728);
	private final static GeneralConversion CubicInchToCubicMeter = new GeneralConversion( 1.0/61024);
	private final static GeneralConversion CubicInchToLiter = new GeneralConversion( 1/61.024);
	private final static GeneralConversion CubicInchToMilliliter = new GeneralConversion( 16.387);
	private final static GeneralConversion CubicInchToUSCup = new GeneralConversion( 1/14.646);
	private final static GeneralConversion CubicInchToUSFluidOunce = new GeneralConversion( 1/1.805);
	private final static GeneralConversion CubicInchToUSGallon = new GeneralConversion( 1.0/231);
	private final static GeneralConversion CubicInchToUSPint = new GeneralConversion( 1/28.875);
	private final static GeneralConversion CubicInchToUSQuart = new GeneralConversion( 1/57.75);
	private final static GeneralConversion CubicInchToUSTablespoon = new GeneralConversion( 1.108);
	private final static GeneralConversion CubicInchToUSTeaspoon = new GeneralConversion( 3.325);
	
	private final static GeneralConversion CubicMeterToCubicFoot = new GeneralConversion( 35.315);
	private final static GeneralConversion CubicMeterToCubicInch = new GeneralConversion( 61024);
	private final static GeneralConversion CubicMeterToLiter = new GeneralConversion( 1000);
	private final static GeneralConversion CubicMeterToMilliliter = new GeneralConversion( 1e+6);
	private final static GeneralConversion CubicMeterToUSCup = new GeneralConversion( 4167);
	private final static GeneralConversion CubicMeterToUSFluidOunce = new GeneralConversion( 33814);
	private final static GeneralConversion CubicMeterToUSGallon = new GeneralConversion( 264);
	private final static GeneralConversion CubicMeterToUSPint = new GeneralConversion( 2113);
	private final static GeneralConversion CubicMeterToUSQuart = new GeneralConversion( 1057);
	private final static GeneralConversion CubicMeterToUSTablespoon = new GeneralConversion( 67628);
	private final static GeneralConversion CubicMeterToUSTeaspoon = new GeneralConversion( 202884);
	
	private final static GeneralConversion LiterToCubicFoot = new GeneralConversion( 1/28.317);
	private final static GeneralConversion LiterToCubicInch = new GeneralConversion( 61.024);
	private final static GeneralConversion LiterToCubicMeter = new GeneralConversion( 1.0/1000);
	private final static GeneralConversion LiterToMilliliter = new GeneralConversion( 1000);
	private final static GeneralConversion LiterToUSCup = new GeneralConversion( 4.167);
	private final static GeneralConversion LiterToUSFluidOunce = new GeneralConversion( 33.814);
	private final static GeneralConversion LiterToUSGallon = new GeneralConversion( 1/3.785);
	private final static GeneralConversion LiterToUSPint = new GeneralConversion( 2.113);
	private final static GeneralConversion LiterToUSQuart = new GeneralConversion( 1.057);
	private final static GeneralConversion LiterToUSTablespoon = new GeneralConversion( 67.628);
	private final static GeneralConversion LiterToUSTeaspoon = new GeneralConversion( 203);
	
	private final static GeneralConversion MilliliterToCubicFoot = new GeneralConversion( 1.0/28317);
	private final static GeneralConversion MilliliterToCubicInch = new GeneralConversion( 1/16.387);
	private final static GeneralConversion MilliliterToCubicMeter = new GeneralConversion( 1.0/1e+6);
	private final static GeneralConversion MilliliterToLiter = new GeneralConversion( 1.0/1000);
	private final static GeneralConversion MilliliterToUSCup = new GeneralConversion( 1.0/240);
	private final static GeneralConversion MilliliterToUSFluidOunce = new GeneralConversion( 1.0/29.574);
	private final static GeneralConversion MilliliterToUSGallon = new GeneralConversion( 1.0/3875);
	private final static GeneralConversion MilliliterToUSPint = new GeneralConversion( 1.0/473);
	private final static GeneralConversion MilliliterToUSQuart = new GeneralConversion( 1.0/946);
	private final static GeneralConversion MilliliterToUSTablespoon = new GeneralConversion( 1/14.787);
	private final static GeneralConversion MilliliterToUSTeaspoon = new GeneralConversion( 1/4.929);
	
	private final static GeneralConversion USCupToCubicFoot = new GeneralConversion( 1.0/118);
	private final static GeneralConversion USCupToCubicInch = new GeneralConversion( 1.0/14.646);
	private final static GeneralConversion USCupToCubicMeter = new GeneralConversion( 1.0/4167);
	private final static GeneralConversion USCupToLiter = new GeneralConversion( 1.0/4.167);
	private final static GeneralConversion USCupToMilliliter = new GeneralConversion( 240);
	private final static GeneralConversion USCupToUSFluidOunce = new GeneralConversion( 8.115);
	private final static GeneralConversion USCupToUSGallon = new GeneralConversion( 1/15.773);
	private final static GeneralConversion USCupToUSPint = new GeneralConversion( 1/1.972);
	private final static GeneralConversion USCupToUSQuart = new GeneralConversion( 1/3.943);
	private final static GeneralConversion USCupToUSTablespoon = new GeneralConversion( 16.231);
	private final static GeneralConversion USCupToUSTeaspoon = new GeneralConversion( 48.692);
	
	private final static GeneralConversion USFluidOunceToCubicFoot = new GeneralConversion( 1.0/958);
	private final static GeneralConversion USFluidOunceToCubicInch = new GeneralConversion( 1.805);
	private final static GeneralConversion USFluidOunceToCubicMeter = new GeneralConversion( 1.0/33814);
	private final static GeneralConversion USFluidOunceToLiter = new GeneralConversion( 1/33.814);
	private final static GeneralConversion USFluidOunceToMilliliter = new GeneralConversion( 29.574);
	private final static GeneralConversion USFluidOunceToUSCup = new GeneralConversion( 1/8.115);
	private final static GeneralConversion USFluidOunceToUSGallon = new GeneralConversion( 1.0/128);
	private final static GeneralConversion USFluidOunceToUSPint = new GeneralConversion( 1.0/16);
	private final static GeneralConversion USFluidOunceToUSQuart = new GeneralConversion( 1.0/32);
	private final static GeneralConversion USFluidOunceToUSTablespoon = new GeneralConversion( 2);
	private final static GeneralConversion USFluidOunceToUSTeaspoon = new GeneralConversion( 6);
	
	private final static GeneralConversion USGallonToCubicFoot = new GeneralConversion( 1/7.481);
	private final static GeneralConversion USGallonToCubicInch = new GeneralConversion( 231);
	private final static GeneralConversion USGallonToCubicMeter = new GeneralConversion( 1.0/264);
	private final static GeneralConversion USGallonToLiter = new GeneralConversion( 3.785);
	private final static GeneralConversion USGallonToMilliliter = new GeneralConversion( 3875);
	private final static GeneralConversion USGallonToUSCup = new GeneralConversion( 15.773);
	private final static GeneralConversion USGallonToUSFluidOunce = new GeneralConversion( 128);
	private final static GeneralConversion USGallonToUSPint = new GeneralConversion( 8);
	private final static GeneralConversion USGallonToUSQuart = new GeneralConversion( 4);
	private final static GeneralConversion USGallonToUSTablespoon = new GeneralConversion( 256);
	private final static GeneralConversion USGallonToUSTeaspoon = new GeneralConversion( 768);
	
	private final static GeneralConversion USPintToCubicFoot = new GeneralConversion( 1/59.844);
	private final static GeneralConversion USPintToCubicInch = new GeneralConversion( 28.875);
	private final static GeneralConversion USPintToCubicMeter = new GeneralConversion( 1.0/2113);
	private final static GeneralConversion USPintToLiter = new GeneralConversion( 1.0/2.113);
	private final static GeneralConversion USPintToMilliliter = new GeneralConversion( 473);
	private final static GeneralConversion USPintToUSCup = new GeneralConversion( 1.972);
	private final static GeneralConversion USPintToUSFluidOunce = new GeneralConversion( 16.0);
	private final static GeneralConversion USPintToUSGallon = new GeneralConversion( 0.125);
	private final static GeneralConversion USPintToUSQuart = new GeneralConversion( 0.5);
	private final static GeneralConversion USPintToUSTablespoon = new GeneralConversion( 32.0);
	private final static GeneralConversion USPintToUSTeaspoon = new GeneralConversion( 96.0);
	
	private final static GeneralConversion USQuartToCubicFoot = new GeneralConversion( 1/29.922);
	private final static GeneralConversion USQuartToCubicInch = new GeneralConversion( 57.75);
	private final static GeneralConversion USQuartToCubicMeter = new GeneralConversion( 1.0/1057);
	private final static GeneralConversion USQuartToLiter = new GeneralConversion( 1/1.057);
	private final static GeneralConversion USQuartToMilliliter = new GeneralConversion( 946);
	private final static GeneralConversion USQuartToUSCup = new GeneralConversion( 3.943);
	private final static GeneralConversion USQuartToUSFluidOunce = new GeneralConversion( 32);
	private final static GeneralConversion USQuartToUSGallon = new GeneralConversion( 0.25);
	private final static GeneralConversion USQuartToUSPint = new GeneralConversion( 2.0);
	private final static GeneralConversion USQuartToUSTablespoon = new GeneralConversion( 64);
	private final static GeneralConversion USQuartToUSTeaspoon = new GeneralConversion( 192);
	
	private final static GeneralConversion USTablespoonToCubicFoot = new GeneralConversion( 1.0/1915);
	private final static GeneralConversion USTablespoonToCubicInch = new GeneralConversion( 1/1.108);
	private final static GeneralConversion USTablespoonToCubicMeter = new GeneralConversion( 1.0/67628);
	private final static GeneralConversion USTablespoonToLiter = new GeneralConversion( 1/67.628);
	private final static GeneralConversion USTablespoonToMilliliter = new GeneralConversion( 14.787);
	private final static GeneralConversion USTablespoonToUSCup = new GeneralConversion( 1/16.231);
	private final static GeneralConversion USTablespoonToUSFluidOunce = new GeneralConversion( 0.5);
	private final static GeneralConversion USTablespoonToUSGallon = new GeneralConversion( 1.0/256);
	private final static GeneralConversion USTablespoonToUSPint = new GeneralConversion( 1.0/32);
	private final static GeneralConversion USTablespoonToUSQuart = new GeneralConversion( 1.0/64);
	private final static GeneralConversion USTablespoonToUSTeaspoon = new GeneralConversion( 3.0);
	
	private final static GeneralConversion USTeaspoonToCubicFoot = new GeneralConversion( 1.0/5745);
	private final static GeneralConversion USTeaspoonToCubicInch = new GeneralConversion( 1/3.325);
	private final static GeneralConversion USTeaspoonToCubicMeter = new GeneralConversion( 1.0/202884);
	private final static GeneralConversion USTeaspoonToLiter = new GeneralConversion( 1.0/203);
	private final static GeneralConversion USTeaspoonToMilliliter = new GeneralConversion( 4.929);
	private final static GeneralConversion USTeaspoonToUSCup = new GeneralConversion( 1/48.692);
	private final static GeneralConversion USTeaspoonToUSFluidOunce = new GeneralConversion( 1.0/6);
	private final static GeneralConversion USTeaspoonToUSGallon = new GeneralConversion( 1.0/768);
	private final static GeneralConversion USTeaspoonToUSPint = new GeneralConversion( 1.0/96);
	private final static GeneralConversion USTeaspoonToUSQuart = new GeneralConversion( 1.0/192);
	private final static GeneralConversion USTeaspoonToUSTablespoon = new GeneralConversion( 1.0/3);

	@Override
	public void Execute() 
	{

		UnitConverterWindow window = UnitConverterController.GetWindow();
		window.ClearUnitSelection();
		window.AddToUnitSelection("Cubic Foot to Cubic Inch",CubicFootToCubicInch);
		window.AddToUnitSelection("Cubic Foot to Cubic Meter",CubicFootToCubicMeter);
		window.AddToUnitSelection("Cubic Foot to Liter",CubicFootToLiter);
		window.AddToUnitSelection("Cubic Foot to Milliliter",CubicFootToMilliliter);
		window.AddToUnitSelection("Cubic Foot to US Cup",CubicFootToUSCup);
		window.AddToUnitSelection("Cubic Foot to US Fluid Ounce",CubicFootToUSFluidOunce);
		window.AddToUnitSelection("Cubic Foot to US Gallon",CubicFootToUSGallon);
		window.AddToUnitSelection("Cubic Foot to US Pint",CubicFootToUSPint);
		window.AddToUnitSelection("Cubic Foot to US Quart",CubicFootToUSQuart);
		window.AddToUnitSelection("Cubic Foot to US Tablespoon",CubicFootToUSTablespoon);
		window.AddToUnitSelection("Cubic Foot to US Teaspoon",CubicFootToUSTeaspoon);
		window.AddToUnitSelection("Cubic Inch to Cubic Foot",CubicInchToCubicFoot);
		window.AddToUnitSelection("Cubic Inch to Cubic Meter",CubicInchToCubicMeter);
		window.AddToUnitSelection("Cubic Inch to Liter",CubicInchToLiter);
		window.AddToUnitSelection("Cubic Inch to Milliliter",CubicInchToMilliliter);
		window.AddToUnitSelection("Cubic Inch to US Cup",CubicInchToUSCup);
		window.AddToUnitSelection("Cubic Inch to US Fluid Ounce",CubicInchToUSFluidOunce);
		window.AddToUnitSelection("Cubic Inch to US Gallon",CubicInchToUSGallon);
		window.AddToUnitSelection("Cubic Inch to US Pint",CubicInchToUSPint);
		window.AddToUnitSelection("Cubic Inch to US Quart",CubicInchToUSQuart);
		window.AddToUnitSelection("Cubic Inch to US Tablespoon",CubicInchToUSTablespoon);
		window.AddToUnitSelection("Cubic Inch to US Teaspoon",CubicInchToUSTeaspoon);
		window.AddToUnitSelection("Cubic Meter to Cubic Foot",CubicMeterToCubicFoot);
		window.AddToUnitSelection("Cubic Meter to Cubic Inch",CubicMeterToCubicInch);
		window.AddToUnitSelection("Cubic Meter to Liter",CubicMeterToLiter);
		window.AddToUnitSelection("Cubic Meter to Milliliter",CubicMeterToMilliliter);
		window.AddToUnitSelection("Cubic Meter to US Cup",CubicMeterToUSCup);
		window.AddToUnitSelection("Cubic Meter to US Fluid Ounce",CubicMeterToUSFluidOunce);
		window.AddToUnitSelection("Cubic Meter to US Gallon",CubicMeterToUSGallon);
		window.AddToUnitSelection("Cubic Meter to US Pint",CubicMeterToUSPint);
		window.AddToUnitSelection("Cubic Meter to US Quart",CubicMeterToUSQuart);
		window.AddToUnitSelection("Cubic Meter to US Tablespoon",CubicMeterToUSTablespoon);
		window.AddToUnitSelection("Cubic Meter to US Teaspoon",CubicMeterToUSTeaspoon);
		window.AddToUnitSelection("Liter to Cubic Foot",LiterToCubicFoot);
		window.AddToUnitSelection("Liter to Cubic Inch",LiterToCubicInch);
		window.AddToUnitSelection("Liter to Cubic Meter",LiterToCubicMeter);
		window.AddToUnitSelection("Liter to Milliliter",LiterToMilliliter);
		window.AddToUnitSelection("Liter to US Cup",LiterToUSCup);
		window.AddToUnitSelection("Liter to US Fluid Ounce",LiterToUSFluidOunce);
		window.AddToUnitSelection("Liter to US Gallon",LiterToUSGallon);
		window.AddToUnitSelection("Liter to US Pint",LiterToUSPint);
		window.AddToUnitSelection("Liter to US Quart",LiterToUSQuart);
		window.AddToUnitSelection("Liter to US Tablespoon",LiterToUSTablespoon);
		window.AddToUnitSelection("Liter to US Teaspoon",LiterToUSTeaspoon);
		window.AddToUnitSelection("Milliliter to Cubic Foot",MilliliterToCubicFoot);
		window.AddToUnitSelection("Milliliter to Cubic Inch",MilliliterToCubicInch);
		window.AddToUnitSelection("Milliliter to Cubic Meter",MilliliterToCubicMeter);
		window.AddToUnitSelection("Milliliter to Liter",MilliliterToLiter);
		window.AddToUnitSelection("Milliliter to US Cup",MilliliterToUSCup);
		window.AddToUnitSelection("Milliliter to US Fluid Ounce",MilliliterToUSFluidOunce);
		window.AddToUnitSelection("Milliliter to US Gallon",MilliliterToUSGallon);
		window.AddToUnitSelection("Milliliter to US Pint",MilliliterToUSPint);
		window.AddToUnitSelection("Milliliter to US Quart",MilliliterToUSQuart);
		window.AddToUnitSelection("Milliliter to US Tablespoon",MilliliterToUSTablespoon);
		window.AddToUnitSelection("Milliliter to US Teaspoon",MilliliterToUSTeaspoon);
		window.AddToUnitSelection("US Cup to Cubic Foot",USCupToCubicFoot);
		window.AddToUnitSelection("US Cup to Cubic Inch",USCupToCubicInch);
		window.AddToUnitSelection("US Cup to Cubic Meter",USCupToCubicMeter);
		window.AddToUnitSelection("US Cup to Liter",USCupToLiter);
		window.AddToUnitSelection("US Cup to Milliliter",USCupToMilliliter);
		window.AddToUnitSelection("US Cup to US Fluid Ounce",USCupToUSFluidOunce);
		window.AddToUnitSelection("US Cup to US Gallon",USCupToUSGallon);
		window.AddToUnitSelection("US Cup to US Pint",USCupToUSPint);
		window.AddToUnitSelection("US Cup to US Quart",USCupToUSQuart);
		window.AddToUnitSelection("US Cup to US Tablespoon",USCupToUSTablespoon);
		window.AddToUnitSelection("US Cup to US Teaspoon",USCupToUSTeaspoon);
		window.AddToUnitSelection("US Fluid Ounce to Cubic Foot",USFluidOunceToCubicFoot);
		window.AddToUnitSelection("US Fluid Ounce to Cubic Inch",USFluidOunceToCubicInch);
		window.AddToUnitSelection("US Fluid Ounce to Cubic Meter",USFluidOunceToCubicMeter);
		window.AddToUnitSelection("US Fluid Ounce to Liter",USFluidOunceToLiter);
		window.AddToUnitSelection("US Fluid Ounce to Milliliter",USFluidOunceToMilliliter);
		window.AddToUnitSelection("US Fluid Ounce to US Cup",USFluidOunceToUSCup);
		window.AddToUnitSelection("US Fluid Ounce to US Gallon",USFluidOunceToUSGallon);
		window.AddToUnitSelection("US Fluid Ounce to US Pint",USFluidOunceToUSPint);
		window.AddToUnitSelection("US Fluid Ounce to US Quart",USFluidOunceToUSQuart);
		window.AddToUnitSelection("US Fluid Ounce to US Tablespoon",USFluidOunceToUSTablespoon);
		window.AddToUnitSelection("US Fluid Ounce to US Teaspoon",USFluidOunceToUSTeaspoon);
		window.AddToUnitSelection("US Gallon to Cubic Foot",USGallonToCubicFoot);
		window.AddToUnitSelection("US Gallon to Cubic Inch",USGallonToCubicInch);
		window.AddToUnitSelection("US Gallon to Cubic Meter",USGallonToCubicMeter);
		window.AddToUnitSelection("US Gallon to Liter",USGallonToLiter);
		window.AddToUnitSelection("US Gallon to Milliliter",USGallonToMilliliter);
		window.AddToUnitSelection("US Gallon to US Cup",USGallonToUSCup);
		window.AddToUnitSelection("US Gallon to US Fluid Ounce",USGallonToUSFluidOunce);
		window.AddToUnitSelection("US Gallon to US Pint",USGallonToUSPint);
		window.AddToUnitSelection("US Gallon to US Quart",USGallonToUSQuart);
		window.AddToUnitSelection("US Gallon to US Tablespoon",USGallonToUSTablespoon);
		window.AddToUnitSelection("US Gallon to US Teaspoon",USGallonToUSTeaspoon);
		window.AddToUnitSelection("US Pint to Cubic Foot",USPintToCubicFoot);
		window.AddToUnitSelection("US Pint to Cubic Inch",USPintToCubicInch);
		window.AddToUnitSelection("US Pint to Cubic Meter",USPintToCubicMeter);
		window.AddToUnitSelection("US Pint to Liter",USPintToLiter);
		window.AddToUnitSelection("US Pint to Milliliter",USPintToMilliliter);
		window.AddToUnitSelection("US Pint to US Cup",USPintToUSCup);
		window.AddToUnitSelection("US Pint to US Fluid Ounce",USPintToUSFluidOunce);
		window.AddToUnitSelection("US Pint to US Gallon",USPintToUSGallon);
		window.AddToUnitSelection("US Pint to US Quart",USPintToUSQuart);
		window.AddToUnitSelection("US Pint to US Tablespoon",USPintToUSTablespoon);
		window.AddToUnitSelection("US Pint to US Teaspoon",USPintToUSTeaspoon);
		window.AddToUnitSelection("US Quart to Cubic Foot",USQuartToCubicFoot);
		window.AddToUnitSelection("US Quart to Cubic Inch",USQuartToCubicInch);
		window.AddToUnitSelection("US Quart to Cubic Meter",USQuartToCubicMeter);
		window.AddToUnitSelection("US Quart to Liter",USQuartToLiter);
		window.AddToUnitSelection("US Quart to Milliliter",USQuartToMilliliter);
		window.AddToUnitSelection("US Quart to US Cup",USQuartToUSCup);
		window.AddToUnitSelection("US Quart to US Fluid Ounce",USQuartToUSFluidOunce);
		window.AddToUnitSelection("US Quart to US Gallon",USQuartToUSGallon);
		window.AddToUnitSelection("US Quart to US Pint",USQuartToUSPint);
		window.AddToUnitSelection("US Quart to US Tablespoon",USQuartToUSTablespoon);
		window.AddToUnitSelection("US Quart to US Teaspoon",USQuartToUSTeaspoon);
		window.AddToUnitSelection("US Tablespoon to Cubic Foot",USTablespoonToCubicFoot);
		window.AddToUnitSelection("US Tablespoon to Cubic Inch",USTablespoonToCubicInch);
		window.AddToUnitSelection("US Tablespoon to Cubic Meter",USTablespoonToCubicMeter);
		window.AddToUnitSelection("US Tablespoon to Liter",USTablespoonToLiter);
		window.AddToUnitSelection("US Tablespoon to Milliliter",USTablespoonToMilliliter);
		window.AddToUnitSelection("US Tablespoon to US Cup",USTablespoonToUSCup);
		window.AddToUnitSelection("US Tablespoon to US Fluid Ounce",USTablespoonToUSFluidOunce);
		window.AddToUnitSelection("US Tablespoon to US Gallon",USTablespoonToUSGallon);
		window.AddToUnitSelection("US Tablespoon to US Pint",USTablespoonToUSPint);
		window.AddToUnitSelection("US Tablespoon to US Quart",USTablespoonToUSQuart);
		window.AddToUnitSelection("US Tablespoon to US Teaspoon",USTablespoonToUSTeaspoon);
		window.AddToUnitSelection("US Teaspoon to Cubic Foot",USTeaspoonToCubicFoot);
		window.AddToUnitSelection("US Teaspoon to Cubic Inch",USTeaspoonToCubicInch);
		window.AddToUnitSelection("US Teaspoon to Cubic Meter",USTeaspoonToCubicMeter);
		window.AddToUnitSelection("US Teaspoon to Liter",USTeaspoonToLiter);
		window.AddToUnitSelection("US Teaspoon to Milliliter",USTeaspoonToMilliliter);
		window.AddToUnitSelection("US Teaspoon to US Cup",USTeaspoonToUSCup);
		window.AddToUnitSelection("US Teaspoon to US Fluid Ounce",USTeaspoonToUSFluidOunce);
		window.AddToUnitSelection("US Teaspoon to US Gallon",USTeaspoonToUSGallon);
		window.AddToUnitSelection("US Teaspoon to US Pint",USTeaspoonToUSPint);
		window.AddToUnitSelection("US Teaspoon to US Quart",USTeaspoonToUSQuart);
		window.AddToUnitSelection("US Teaspoon to US Tablespoon",USTeaspoonToUSTablespoon);


	}

}
